### ISSUE TITLE
Can this be integrated with a Circle CI workflow?

### ISSUE THREAD

**Issue by springcoil** [mgibeau/semantic-release-expo-github-action#1]
Hi @mgibeau this looks very cool. One of my questions is if I already have a Circle CI workflow - which I use for deplying to testflight etc. Can this work with it. 

For example can I commit -> increase all the versions -> deploy to circle ci

**Comment by mgibeau** [comment]
Yup, although I think your case, you might want to run this directly in CircleCI rather using Github actions as an intermediate, you can see how to do this here: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/circleci-workflows.md
